[package]
name = "location_history"
version = "0.1.0"
authors = ["Thomas 'Panda' Attwood | TickleThePanda <thomas.pg.attwood@gmail.com>"]

[dependencies]
chrono = "0.4"
libc = "0.2"
image = "0.19.0"
hyper = "0.11"
futures = "0.1.21"
lazy_static = "1.0"
url = "1.7.0"

